### ISSUE TITLE
Make package docu accesible with `texdoc`

### ISSUE THREAD

**Issue by ghost** [minad/slide#1]
You're README.md is a really nice and easy to understand introduction to your package. Would it be possible mark it (or maybe better a `.pdf` version of it) as the documentation of your package the next time you sent an update of your package to CTAN?

Currently `texdoc gridslides` opens `chain_nontrivial.pdf` as "documentation" of your package.

**Comment by minad** [comment]
Thank you for the report! I will fix this in the next version.

**Comment by ghost** [comment]
@minad Thank you!

**Comment by minad** [comment]
Added https://github.com/minad/gridslides/blob/master/gridslides.pdf. I hope that solves it.
