### ISSUE TITLE
Add screenshots to README.md

### ISSUE THREAD

**Issue by rswgnu** [minad/slide#3]
Hi Daniel:

Since this package is about creating slides that have a certain structure and look a certain way, I would suggest you add screenshots to each README.md example you show.  Then someone could see what the output looks like and decide whether or not to use your package, in part based on the results.

**Comment by minad** [comment]
Hmm, a screenshot will be quite meaningless. You can place boxes with images and Tex content on a grid. What you do with this is flexible. See example.pdf as an example.
